export const APP_NAME = 'FUSION HUB';
export const BOT_NAME = 'Fusion Bot';
export const LEGAL_ENTITY_NAME = 'CHAUDHARY TANMAY';
export const BUSINESS_NAME = 'FUSIONBOT (FUSIONHUB)';
export const OPERATIONAL_ADDRESS = 'FusionHub Internet & Digital Services, Delhi NCR, India';
export const SUPPORT_EMAIL = 'support@fusionhub.in';
export const SUPPORT_HOURS = '10:00 AM – 8:00 PM IST (Mon - Sat) | 24/7 Discord Live Support';
export const DISCORD_INVITE_URL = 'https://discord.com/oauth2/authorize?client_id=1485375910562758967&permissions=8&integration_type=0&scope=bot';
export const DASHBOARD_URL = 'https://panel.fusionhub.in/';
export const SUPPORT_SERVER_URL = 'https://discord.gg/qc26U4WVfF';
export const COMMUNITY_URL = 'https://discord.gg/QK8KJrZv55';
export const YOUTUBE_URL = 'https://www.youtube.com/@tpggamer1';
export const GITHUB_URL = 'https://github.com/fusionhub122-ux';
export const LOGO_URL = 'https://i.ibb.co/vC79Nthr/Whats-App-Image-2026-03-23-at-6-49-47-PM.jpg';
export const TOPGG_URL = 'https://top.gg/bot/1485375910562758967';
export const TOPGG_VOTE_URL = 'https://top.gg/bot/1485375910562758967/vote';
